backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - name: "homepage"
        label: "Homepage Images"
        file: "content/site.yml"
        fields:
          - { label: "Drafting Image", name: "drafting_image", widget: "image" }
          - { label: "2D Illustration Image", name: "drawing_image", widget: "image" }
          - { label: "3D Exploded Preview", name: "exploded_preview", widget: "image" }
